apiVersion: v1
kind: Service
metadata:
  name: lab-numbers-api # 도메인 네임 // 틀렸음
spec:
  ports:
    - port: 80
  selector:
    app: lab-numbers-api
    version: v1
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: lab-numbers-web # 도메인 네임 // 틀렸음
spec:
  ports:
    - port: 8088
      targetPort: 80
  selector:
    app: lab-numbers-web
    version: v2
  type: LoadBalancer