apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    kiamol: ch10-lab
# ConfigController.Enabled should be parameterized
data:
  config.json: |-
    {
      "ConfigController": {
        "Enabled" : {{.Values.configControllerEnabled}}             
      }
    } 