apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}    # this needs to be templated
  labels:
    kiamol: ch10-lab
spec:
  ports:
    - port: {{ .Values.servicePort}}         # this should be parameterized
      targetPort: 80
  selector:              # this needs to be templated
    app: {{ .Release.Name }}
    environment: {{.Values.environment}}
  type: LoadBalancer     # this should be parameterized