apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-web-lab-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: Service
metadata:
  name: todo-web-lab
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: todo-web-lab
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-web-lab
spec:
  selector:
    matchLabels:
      app: todo-web-lab
  template:
    metadata:
      labels:
        app: todo-web-lab
    spec:
      containers:
        - name: web
          image: kiamol/ch04-todo-list
          env:
          - name: Database__Provider
            value: Sqlite
          - name: ConnectionStrings__ToDoDb
            value: "Filename=/data/todo-list-lab.db"
          volumeMounts:
            - name: data            
              mountPath: /data  # 프록시의 캐시 저장 경로          
      volumes:
        - name: data  
          persistentVolumeClaim:            # 영구볼륨클레임을 볼륨으로 사용
            claimName: todo-web-lab-pvc         # 사용할 영구볼륨클레임의 이름